config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks

  root 'user_tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_task.rb
class UserTask < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]

  # GET /user_tasks
  # GET /user_tasks.json
  def index
  end

  # GET /user_tasks/1
  # GET /user_tasks/1.json
  def show
  end

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # GET /user_tasks/1/edit
  def edit
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = UserTask.new(user_task_params)

    respond_to do |format|
      if @user_task.save
        format.html { redirect_to @user_task, notice: 'User task was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: @user_task }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        format.html { redirect_to @user_task, notice: 'User task was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @user_task }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tasks/1
  # DELETE /user_tasks/1.json
  def destroy
    @user_task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'User task was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = UserTask.find(params[:id])
    end

    def all_tasks
      @user_tasks = UserTask.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>

app/views/user_tasks/_datepicker.js.erb
$(document).ready(function (){
  $('#user_task_due').datepicker({
    autoclose: true,
    todayHighlight: true,
    toggleActive: true,
    format: "yyyy-mm-dd",
    orientation: "top auto"
  });
});

app/views/user_tasks/_form.html.erb
<%= simple_form_for(@user_task, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description, as: :text, placeholder: "Made Groceries" %>
    <%= f.input :due, as: :string, placeholder: "Today!" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_tasks/_user_task.html.erb
<div class="well">
  <%= user_task.description %>
  <%= user_task.due %>
  <%= link_to 'Edit', edit_user_task_path(user_task), remote: true %>
  <%= link_to 'Delete', user_task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/user_tasks/create.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

$('#task-form').slideUp(350);

app/views/user_tasks/destroy.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form', user_task: @user_task %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);
  
  <%= render 'datepicker' %>

app/views/user_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Tasks</h1>

<%= link_to 'New User Task', new_user_task_path,
                             remote: true,
                             class: 'btn btn-default' %>

<br>

<div id="task-form"></div>

<br>

<div id="tasks">
  <%= render @user_tasks %>
</div>

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form', user_task: @user_task %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);
  
  <%= render 'datepicker' %>

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
$('#tasks').html("<%= j (render @user_tasks) %>");

$('#task-form').slideUp(350);